// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufxklpfeaugfesbpwhyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmeGtscGZlYXVnZmVzYnB3aHl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MDk1NjYsImV4cCI6MjA3MTE4NTU2Nn0.7SKMMQXkiHHxgFngKn12eZ45y8c42_8lYN6safsT_hA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});